apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: bWVuZGVs  
  mongo-root-password: MTIz
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-tls
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-cert>
  tls.key: <base64-encoded-private-key>
